### PR TITLE
Coffee break!

### PR DESCRIPTION
**Pull request by ghost**
Saw this in the README.md screenshot, which would need to be remade if you accept.

### CODE REVIEW

**Comment by dolfje** [comment]
Thanks ;) Screenshot still need to be remade ;)

**Comment by ghost** [comment]
Probably worth doing it on someone else's machine...

untitled

**Comment by dolfje** [comment]
What system are you on? So we can add it to our test suite.

**Comment by dolfje** [comment]
I already added a preliminary fix. But can't test if other commands fail on your setup. So please post an issue when it isn't solved.

**Comment by ghost** [comment]
Arch.  I'll take another look tonight and add an issue if I still seem to have a problem.

**Pull request merged**
